# Generated by Django 3.0.8 on 2020-07-25 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_Id', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('MiddleName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Address1', models.CharField(max_length=500)),
                ('Address2', models.CharField(max_length=500)),
                ('City', models.CharField(max_length=255)),
                ('PinCode', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=13)),
                ('Email', models.CharField(max_length=310)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField()),
                ('IsCash', models.BooleanField(default=False)),
                ('IsCheque', models.BooleanField(default=False)),
                ('BankName', models.CharField(blank=True, max_length=255, null=True)),
                ('ChequeNo', models.CharField(blank=True, max_length=255, null=True)),
                ('IsOnline', models.BooleanField(default=False)),
                ('PlatformName', models.CharField(blank=True, max_length=255, null=True)),
                ('TransactionId', models.CharField(blank=True, max_length=500, null=True)),
                ('TotalAmount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('DeliveryDate', models.DateField(blank=True, null=True)),
                ('FK_Customer_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.Customer')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
